<a href="https://colab.research.google.com/github/hahajjjun/Machine_Learning_Toy_Projects/blob/main/SVD%20from%20EVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [100]:
import numpy as np
from numpy.linalg import eigh #eigh can solve eigenvalue sign issue when we use eig
from numpy.linalg import svd
import math

In [101]:
a = np.array([[1,2,3],[4,5,6]])

In [102]:
# Transpose
print(a)
print(a.transpose())

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [103]:
M1 = a.dot(a.transpose()) # M1 = A A^T
M2 = a.transpose().dot(a) # M2 = A^T A
print(M1)
print(M2)

[[14 32]
 [32 77]]
[[17 22 27]
 [22 29 36]
 [27 36 45]]


In [104]:
def sortbyeigval(eigenValues, eigenVectors): # 두 차례 Eigenvalue Decomposition했을 때 eigenvalue 순서대로 정렬하고 부호도 통일해야 함!
  idx = np.argsort(eigenValues)[::-1]
  eigenValues = eigenValues[idx]
  eigenVectors = eigenVectors[:,idx]
  return (eigenValues, eigenVectors)

def KillArithmeticError(eigenValues): # 0보다 작은 값은 불가능한데, 부동소수점 오차처럼 발생하는 오류임.
  evals = []
  for eval in eigenValues:
    if eval < 0 :
      eval = 0
    evals.append(eval)
  
  return np.array(evals)


In [105]:
eval1, evec1 = eigh(M1)
eval2, evec2 = eigh(M2)
eigval1, eigvec1 = sortbyeigval(eval1, evec1)
eigval2, eigvec2 = sortbyeigval(eval2, evec2)

eigval1 = KillArithmeticError(eigval1)
eigval2 = KillArithmeticError(eigval2)

print(f"Eigenvalues of M1 : {eigval1} \n Eigenvalues of M2 : {eigval2}")
print("There are same eigenvalues, but not identical")
print(f"Eigenvectors of M1 : {eigvec1} \n Eigenvectors of M2 : {eigvec2}")

Eigenvalues of M1 : [90.40267253  0.59732747] 
 Eigenvalues of M2 : [90.40267253  0.59732747  0.        ]
There are same eigenvalues, but not identical
Eigenvectors of M1 : [[ 0.3863177  -0.92236578]
 [ 0.92236578  0.3863177 ]] 
 Eigenvectors of M2 : [[-0.42866713 -0.80596391  0.40824829]
 [-0.56630692 -0.11238241 -0.81649658]
 [-0.7039467   0.58119908  0.40824829]]


In [106]:
# Verify that Matrix is normal
for i in range(a.shape[0]):
  for j in range(a.shape[0]):
    print(f"M1 : Dot product of {i}th eigenvector and {j}th eigenvenctor :   {eigvec1[i].dot(eigvec1[j])}")

for i in range(a.shape[1]):
  for j in range(a.shape[1]):
    print(f"M2 : Dot product of {i}th eigenvector and {j}th eigenvenctor :   {eigvec2[i].dot(eigvec2[j])}")

M1 : Dot product of 0th eigenvector and 0th eigenvenctor :   1.0000000000000002
M1 : Dot product of 0th eigenvector and 1th eigenvenctor :   -1.2496472896191782e-17
M1 : Dot product of 1th eigenvector and 0th eigenvenctor :   -1.2496472896191782e-17
M1 : Dot product of 1th eigenvector and 1th eigenvenctor :   1.0000000000000002
M2 : Dot product of 0th eigenvector and 0th eigenvenctor :   0.9999999999999999
M2 : Dot product of 0th eigenvector and 1th eigenvenctor :   1.0664757969207052e-16
M2 : Dot product of 0th eigenvector and 2th eigenvenctor :   1.400401499627867e-16
M2 : Dot product of 1th eigenvector and 0th eigenvenctor :   1.0664757969207052e-16
M2 : Dot product of 1th eigenvector and 1th eigenvenctor :   0.9999999999999991
M2 : Dot product of 1th eigenvector and 2th eigenvenctor :   2.1462947648073227e-16
M2 : Dot product of 2th eigenvector and 0th eigenvenctor :   1.400401499627867e-16
M2 : Dot product of 2th eigenvector and 1th eigenvenctor :   2.1462947648073227e-16
M2 : Dot

In [107]:
U = -np.array(eigvec1)
V = np.array(eigvec2)
Ut = U.transpose()
Vt = V.transpose()
Sigma = np.zeros(a.shape)
singular = np.vectorize(lambda x : math.sqrt(x))(eigval1)
np.fill_diagonal(Sigma, singular)
A = U.dot(Sigma).dot(Vt)
print(U)
print(Sigma)
print(Vt)
print(A)

[[-0.3863177   0.92236578]
 [-0.92236578 -0.3863177 ]]
[[9.508032   0.         0.        ]
 [0.         0.77286964 0.        ]]
[[-0.42866713 -0.56630692 -0.7039467 ]
 [-0.80596391 -0.11238241  0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]
[[1. 2. 3.]
 [4. 5. 6.]]
